const ZEME = [
  {title: '🇦🇹 Rakousko', value: 'AT'},
  {title: '🇧🇪 Belgie', value: 'BE'},
  {title: '🇧🇬 Bulharsko', value: 'BG'},
  {title: '🇭🇷 Chorvatsko', value: 'HR'},
  {title: '🇨🇾 Kypr', value: 'CY'},
  {title: '🇨🇿 Česko', value: 'CZ'},
  {title: '🇩🇰 Dánsko', value: 'DK'},
  {title: '🇪🇪 Estonsko', value: 'EE'},
  {title: '🇫🇮 Finsko', value: 'FI'},
  {title: '🇫🇷 Francie', value: 'FR'},
  {title: '🇩🇪 Německo', value: 'DE'},
  {title: '🇬🇷 Řecko', value: 'GR'},
  {title: '🇭🇺 Maďarsko', value: 'HU'},
  {title: '🇮🇸 Island', value: 'IS'},
  {title: '🇮🇪 Irsko', value: 'IE'},
  {title: '🇮🇹 Itálie', value: 'IT'},
  {title: '🇱🇻 Lotyšsko', value: 'LV'},
  {title: '🇱🇮 Lichtenštejnsko', value: 'LI'},
  {title: '🇱🇹 Litva', value: 'LT'},
  {title: '🇱🇺 Lucembursko', value: 'LU'},
  {title: '🇲🇹 Malta', value: 'MT'},
  {title: '🇳🇱 Nizozemsko', value: 'NL'},
  {title: '🇲🇰 Severní Makedonie', value: 'MK'},
  {title: '🇳🇴 Norsko', value: 'NO'},
  {title: '🇵🇱 Polsko', value: 'PL'},
  {title: '🇵🇹 Portugalsko', value: 'PT'},
  {title: '🇷🇴 Rumunsko', value: 'RO'},
  {title: '🇷🇸 Srbsko', value: 'RS'},
  {title: '🇸🇰 Slovensko', value: 'SK'},
  {title: '🇸🇮 Slovinsko', value: 'SI'},
  {title: '🇪🇸 Španělsko', value: 'ES'},
  {title: '🇸🇪 Švédsko', value: 'SE'},
  {title: '🇹🇷 Turecko', value: 'TR'},
]

export default {
  name: 'aktualniProjekt',
  title: 'Aktuální projekt',
  type: 'document',
  fields: [
    {
      name: 'nazev',
      title: 'Název projektu',
      type: 'string',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'typ',
      title: 'Typ projektu',
      type: 'string',
      options: {
        list: [
          {title: 'Výměna mládeže', value: 'vymena'},
          {title: 'Tréninkový kurz', value: 'trening'},
        ],
      },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'zeme',
      title: 'Země',
      type: 'string',
      options: {
        list: ZEME,
      },
      description: 'Vyber zemi ze seznamu, vlajka se doplní automaticky',
    },
    {
      name: 'mesto',
      title: 'Město',
      type: 'string',
    },
    {
      name: 'datum',
      title: 'Datum (text)',
      type: 'string',
      description: 'Např. "14.–24. září 2026"',
    },
    {
      name: 'deadlinePrihlasky',
      title: 'Deadline pro přihlášení',
      type: 'date',
      description: 'Do kdy se lze přihlásit — po tomto datu se na webu zobrazí "Uzavřeno"',
      options: {
        dateFormat: 'DD.MM.YYYY',
      },
    },
    {
      name: 'pocetUcastniku',
      title: 'Počet účastníků',
      type: 'number',
    },
    {
      name: 'groupLeaderi',
      title: 'Počet group leaderů',
      type: 'number',
      description: 'Volitelné, +1 nebo +2 group leadeři',
    },
    {
      name: 'vekOd',
      title: 'Věk od',
      type: 'number',
      description: 'Minimální věk účastníka',
    },
    {
      name: 'vekDo',
      title: 'Věk do',
      type: 'number',
      description: 'Maximální věk účastníka',
    },
    {
      name: 'popis',
      title: 'Popis',
      type: 'text',
      rows: 4,
    },
    {
      name: 'fotka',
      title: 'Hlavní fotka',
      type: 'image',
      options: {hotspot: true},
    },
    {
      name: 'odkazPrihlaska',
      title: 'Odkaz na přihlášku',
      type: 'url',
    },
    {
      name: 'odkazInfopack',
      title: 'Odkaz na infopack',
      type: 'url',
    },
  ],
  preview: {
    select: {
      title: 'nazev',
      subtitle: 'mesto',
      media: 'fotka',
    },
  },
}